# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fraiss_c/rendu/tek2/B4/B4-C++2/indiestudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fraiss_c/rendu/tek2/B4/B4-C++2/indiestudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fraiss_c/rendu/tek2/B4/B4-C++2/indiestudio/CMakeFiles /home/fraiss_c/rendu/tek2/B4/B4-C++2/indiestudio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fraiss_c/rendu/tek2/B4/B4-C++2/indiestudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indiestudio

# Build rule for target.
indiestudio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indiestudio
.PHONY : indiestudio

# fast build rule for target.
indiestudio/fast:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/build
.PHONY : indiestudio/fast

src/EventReceiver.o: src/EventReceiver.cpp.o

.PHONY : src/EventReceiver.o

# target to build an object file
src/EventReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/EventReceiver.cpp.o
.PHONY : src/EventReceiver.cpp.o

src/EventReceiver.i: src/EventReceiver.cpp.i

.PHONY : src/EventReceiver.i

# target to preprocess a source file
src/EventReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/EventReceiver.cpp.i
.PHONY : src/EventReceiver.cpp.i

src/EventReceiver.s: src/EventReceiver.cpp.s

.PHONY : src/EventReceiver.s

# target to generate assembly for a file
src/EventReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/EventReceiver.cpp.s
.PHONY : src/EventReceiver.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/MenuMainPage.o: src/MenuMainPage.cpp.o

.PHONY : src/MenuMainPage.o

# target to build an object file
src/MenuMainPage.cpp.o:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/MenuMainPage.cpp.o
.PHONY : src/MenuMainPage.cpp.o

src/MenuMainPage.i: src/MenuMainPage.cpp.i

.PHONY : src/MenuMainPage.i

# target to preprocess a source file
src/MenuMainPage.cpp.i:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/MenuMainPage.cpp.i
.PHONY : src/MenuMainPage.cpp.i

src/MenuMainPage.s: src/MenuMainPage.cpp.s

.PHONY : src/MenuMainPage.s

# target to generate assembly for a file
src/MenuMainPage.cpp.s:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/MenuMainPage.cpp.s
.PHONY : src/MenuMainPage.cpp.s

src/MenuSettingsPage.o: src/MenuSettingsPage.cpp.o

.PHONY : src/MenuSettingsPage.o

# target to build an object file
src/MenuSettingsPage.cpp.o:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/MenuSettingsPage.cpp.o
.PHONY : src/MenuSettingsPage.cpp.o

src/MenuSettingsPage.i: src/MenuSettingsPage.cpp.i

.PHONY : src/MenuSettingsPage.i

# target to preprocess a source file
src/MenuSettingsPage.cpp.i:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/MenuSettingsPage.cpp.i
.PHONY : src/MenuSettingsPage.cpp.i

src/MenuSettingsPage.s: src/MenuSettingsPage.cpp.s

.PHONY : src/MenuSettingsPage.s

# target to generate assembly for a file
src/MenuSettingsPage.cpp.s:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/MenuSettingsPage.cpp.s
.PHONY : src/MenuSettingsPage.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/indiestudio.dir/build.make CMakeFiles/indiestudio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... indiestudio"
	@echo "... src/EventReceiver.o"
	@echo "... src/EventReceiver.i"
	@echo "... src/EventReceiver.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/MenuMainPage.o"
	@echo "... src/MenuMainPage.i"
	@echo "... src/MenuMainPage.s"
	@echo "... src/MenuSettingsPage.o"
	@echo "... src/MenuSettingsPage.i"
	@echo "... src/MenuSettingsPage.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

